# Generated by Django 4.2.9 on 2024-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
