# Generated by Django 4.2.9 on 2024-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
