# Generated by Django 4.2.9 on 2024-02-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.class'),
        ),
    ]
