# Generated by Django 4.2.9 on 2024-02-20 13:47

import booking.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_alter_booking_description_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(0, '9:00-9:45'), (1, '10:00-10:45'), (2, '11:00-11:45'), (3, '14:00-14:45'), (4, '15:00-15:45'), (5, '16:00-16:45'), (6, '17:00-17:45'), (7, '18:00-18:45')], default=0, validators=[booking.models.validate_time_period]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'date_time')},
        ),
    ]
