# Generated by Django 4.2.9 on 2024-03-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_booking_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date_time',
            new_name='date',
        ),
    ]
